/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.ModelStudent;
import Service.ServiceStudent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ViewStudent extends javax.swing.JFrame {
    
    private ServiceStudent serviceStudent = new ServiceStudent();
    /**
     * Creates new form ViewStudent
     */
    public ViewStudent(){
        initComponents();
        buttonGroup1.add(gender1Text);
        buttonGroup1.add(gender2Text);
        ViewTable();
    }
    
    public void DefaultInformation(){
        this.idText.setText("");
        this.last_nameTextStudent.setText("");
        this.first_nameText.setText("");
        buttonGroup1.clearSelection();
        this.birthdayText.setText("");
        this.emailText.setText("");
        this.phoneText.setText("");
        this.classroomText.setText("");
    }
    
    public ModelStudent getInformation(){
        ModelStudent student;
        
        String id = this.idText.getText();
        String last_name = this.last_nameTextStudent.getText();
        String first_name = this.first_nameText.getText();
        String birthday = this.birthdayText.getText();
        String gender; 
        if(gender1Text.isSelected()) gender = gender1Text.getText();
        else gender = gender2Text.getText();
        String phone = this.phoneText.getText();
        String email = this.emailText.getText();
        String id_classroom = this.classroomText.getText();
        student = new ModelStudent(id,last_name,first_name,birthday,gender,phone,email,id_classroom);
        
        return student;
    }
    
    public void setInformation(ModelStudent student){
        this.idText.setText(student.getId());
        this.last_nameTextStudent.setText(student.getLast_name());
        this.first_nameText.setText(student.getFirst_name());
        if(student.getGender().equals("Male")){
            this.gender1Text.setSelected(true);
        }else{
            this.gender2Text.setSelected(true);
        }
        this.birthdayText.setText(student.getBirthday());
        this.emailText.setText(student.getEmail());
        this.phoneText.setText(student.getPhone());
        this.classroomText.setText(student.getId_classroom());
    }
    
    public void ViewTable(){
        ArrayList<ModelStudent> studentList = serviceStudent.showInformationTable();
        
        DefaultTableModel tblModel = (DefaultTableModel) studentTable.getModel();
        for(ModelStudent student : studentList){
            String data[] ={student.getId(),student.getLast_name(), student.getFirst_name(),student.getBirthday()
                    ,student.getGender(),student.getPhone(),student.getEmail(),student.getId_classroom()};
            tblModel.addRow(data);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        headerStudent = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        last_nameLabelStudent = new javax.swing.JLabel();
        last_nameTextStudent = new javax.swing.JTextField();
        first_nameLabel = new javax.swing.JLabel();
        first_nameText = new javax.swing.JTextField();
        birthdayLabel = new javax.swing.JLabel();
        birthdayText = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        gender1Text = new javax.swing.JCheckBox();
        gender2Text = new javax.swing.JCheckBox();
        phoneLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        classroomLabel = new javax.swing.JLabel();
        classroomText = new javax.swing.JTextField();
        phoneText = new javax.swing.JTextField();
        btADD = new javax.swing.JButton();
        btSEARCH = new javax.swing.JButton();
        btDELETE = new javax.swing.JButton();
        btEDIT = new javax.swing.JButton();
        btRETURN = new javax.swing.JButton();
        btREFRESH = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MANAGER STUDENT");

        headerStudent.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headerStudent.setText("Manager Student");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(headerStudent)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(headerStudent)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        idLabel.setText("ID: ");

        idText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        last_nameLabelStudent.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        last_nameLabelStudent.setText("Last_name:");

        last_nameTextStudent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        first_nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        first_nameLabel.setText("First_name: ");

        first_nameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        birthdayLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        birthdayLabel.setText("Birthday: ");

        birthdayText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        genderLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        genderLabel.setText("Gender: ");

        gender1Text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gender1Text.setText("Male");
        gender1Text.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gender1Text.setMaximumSize(new java.awt.Dimension(80, 29));
        gender1Text.setMinimumSize(new java.awt.Dimension(80, 29));
        gender1Text.setPreferredSize(new java.awt.Dimension(64, 29));

        gender2Text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gender2Text.setText("Fermale");

        phoneLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        phoneLabel.setText("Phone: ");

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        emailLabel.setText("Email: ");

        emailText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        classroomLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        classroomLabel.setText("Classroom: ");

        classroomText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        phoneText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btADD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btADD.setText("ADD ");
        btADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btADDActionPerformed(evt);
            }
        });

        btSEARCH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btSEARCH.setText("SEARCH");
        btSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSEARCHActionPerformed(evt);
            }
        });

        btDELETE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btDELETE.setText("DELETE");
        btDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDELETEActionPerformed(evt);
            }
        });

        btEDIT.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btEDIT.setText("EDIT");
        btEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEDITActionPerformed(evt);
            }
        });

        btRETURN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btRETURN.setText("RETURN");
        btRETURN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRETURNActionPerformed(evt);
            }
        });

        btREFRESH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btREFRESH.setText("REFRESH");
        btREFRESH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btREFRESHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(birthdayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(last_nameLabelStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(first_nameLabel))
                    .addComponent(btADD, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(birthdayText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                        .addComponent(first_nameText, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(last_nameTextStudent, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(idText, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(classroomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(gender1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gender2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emailText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(classroomText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btEDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btRETURN, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(btREFRESH, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gender1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gender2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(last_nameLabelStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(last_nameTextStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(first_nameLabel)
                            .addComponent(first_nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(birthdayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(classroomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(classroomText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(birthdayText)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btADD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRETURN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btREFRESH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Last_name", "First_name", "Birthday", "Gender", "Phone", "Email", "Classroom"
            }
        ));
        studentTable.setAlignmentX(1.0F);
        studentTable.setAlignmentY(1.0F);
        studentTable.setSelectionBackground(new java.awt.Color(153, 255, 255));
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(studentTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDELETEActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) studentTable.getModel();
        
        if(studentTable.getSelectedRowCount() == 1){
            tblModel.removeRow(studentTable.getSelectedRow());
            String id = this.idText.getText();
            try {
                serviceStudent.deleteStudent(id);
            } catch (SQLException ex) {
                Logger.getLogger(ViewStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
            DefaultInformation();
            JOptionPane.showMessageDialog(this, "Delete Succesfull...!!");
        }else{
            if(studentTable.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Table is Empty...");
            }else{
                JOptionPane.showMessageDialog(this, "Please select Single Row for Delete...");
            }
        }
    }//GEN-LAST:event_btDELETEActionPerformed

    private void btADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btADDActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) studentTable.getModel();
        ModelStudent student = getInformation();
        if(student.getId().equals("") || student.getLast_name().equals("") || student.getFirst_name().equals("")
                || student.getBirthday().equals("") || student.getGender().equals("") || student.getEmail().equals("")
                || student.getPhone().equals("") || student.getId_classroom().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter All Data...");
        }
        else{
            if(serviceStudent.checkId(student.getId())){
                JOptionPane.showMessageDialog(this, "Enter new ID...");
            }
            else{
                serviceStudent.addStudent(student);
                JOptionPane.showMessageDialog(this, "Add Data Successfull... !!");
                DefaultInformation();
                tblModel.addRow(new Object[]{student.getId(),student.getLast_name(), student.getFirst_name(),student.getBirthday()
                    ,student.getGender(),student.getPhone(),student.getEmail(),student.getId_classroom()});
            }
        }
        
    }//GEN-LAST:event_btADDActionPerformed

    private void btEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEDITActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) studentTable.getModel();
        if(studentTable.getSelectedRowCount() == 1){
            ModelStudent student = getInformation();
            serviceStudent.updateStudent(student, tblModel.getValueAt(studentTable.getSelectedRow(),0).toString());
            
            tblModel.setValueAt(student.getId(),studentTable.getSelectedRow(),0);
            tblModel.setValueAt(student.getLast_name(),studentTable.getSelectedRow(),1);
            tblModel.setValueAt(student.getFirst_name(),studentTable.getSelectedRow(),2);
            tblModel.setValueAt(student.getBirthday(),studentTable.getSelectedRow(),3);
            tblModel.setValueAt(student.getGender(),studentTable.getSelectedRow(),4);
            tblModel.setValueAt(student.getPhone(),studentTable.getSelectedRow(),5);
            tblModel.setValueAt(student.getEmail(),studentTable.getSelectedRow(),6);
            tblModel.setValueAt(student.getId_classroom(),studentTable.getSelectedRow(),7);
            
            JOptionPane.showMessageDialog(this, "Update Successfull...!!");
        }else{
            if(studentTable.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty...");
            }else{
                JOptionPane.showMessageDialog(this,"Please select Single Row for Update...");
            }
        }
    }//GEN-LAST:event_btEDITActionPerformed
    
    private void btSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSEARCHActionPerformed
        // TODO add your handling code here:
        if(this.idText.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter ID for Search...!!");
        }else{
            if(serviceStudent.checkId(this.idText.getText())){
                String idSearch = this.idText.getText();
                ModelStudent studentSearch = serviceStudent.searchStudent(idSearch);
                DefaultTableModel tblModel = (DefaultTableModel) studentTable.getModel();
                
                int rowLength = tblModel.getRowCount();
                for(int i =0; i< rowLength; i++){
                    if(Objects.equals(studentSearch.getId(), (String) studentTable.getValueAt(i, 0))){
                        studentTable.addRowSelectionInterval(i,i);
                        setInformation(studentSearch);
                        break;
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "ID don't have in data. Enter Id Again...!");
            }
        }
    }//GEN-LAST:event_btSEARCHActionPerformed

    private void btRETURNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRETURNActionPerformed
        ViewController viewController = new ViewController();
        viewController.show();
        setVisible(false);
    }//GEN-LAST:event_btRETURNActionPerformed

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) studentTable.getModel();
        
        String id = tblModel.getValueAt(studentTable.getSelectedRow(),0).toString();
        String last_name = tblModel.getValueAt(studentTable.getSelectedRow(),1).toString();
        String first_name = tblModel.getValueAt(studentTable.getSelectedRow(),2).toString();
        String birthday = tblModel.getValueAt(studentTable.getSelectedRow(),3).toString();
        String gender = tblModel.getValueAt(studentTable.getSelectedRow(),4).toString();
        String phone = tblModel.getValueAt(studentTable.getSelectedRow(),5).toString();
        String email = tblModel.getValueAt(studentTable.getSelectedRow(),6).toString();
        String classroom = tblModel.getValueAt(studentTable.getSelectedRow(),7).toString();
        
        this.idText.setText(id);
        this.last_nameTextStudent.setText(last_name);
        this.first_nameText.setText(first_name);
        this.birthdayText.setText(birthday);
        if(gender.equals("Male")){
            this.gender1Text.setSelected(true);
        }else{
            this.gender2Text.setSelected(true);
        }
        this.phoneText.setText(phone);
        this.emailText.setText(email);
        this.classroomText.setText(classroom);
    }//GEN-LAST:event_studentTableMouseClicked

    private void btREFRESHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btREFRESHActionPerformed
        // TODO add your handling code here:
        DefaultInformation();
        studentTable.getSelectionModel().clearSelection();
    }//GEN-LAST:event_btREFRESHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewStudent().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JTextField birthdayText;
    private javax.swing.JButton btADD;
    private javax.swing.JButton btDELETE;
    private javax.swing.JButton btEDIT;
    private javax.swing.JButton btREFRESH;
    private javax.swing.JButton btRETURN;
    private javax.swing.JButton btSEARCH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel classroomLabel;
    private javax.swing.JTextField classroomText;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel first_nameLabel;
    private javax.swing.JTextField first_nameText;
    private javax.swing.JCheckBox gender1Text;
    private javax.swing.JCheckBox gender2Text;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel headerStudent;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel last_nameLabelStudent;
    private javax.swing.JTextField last_nameTextStudent;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneText;
    private javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables
}
