/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.ModelTeacher;
import Service.ServiceTeacher;
import java.util.ArrayList;
import java.util.Objects;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class ViewTeacher extends javax.swing.JFrame {
    private ServiceTeacher serviceTeacher = new ServiceTeacher();
    /**
     * Creates new form ViewTeacher
     */
    public ViewTeacher() {
        initComponents();
        buttonGroup1.add(gender1Text);
        buttonGroup1.add(gender2Text);
        ViewTable();
    }
    
    public void DefaultInformation(){
        this.idText.setText("");
        this.last_nameText.setText("");
        this.first_nameText.setText("");
        buttonGroup1.clearSelection();
        this.birthdayText.setText("");
        this.emailText.setText("");
        this.phoneText.setText("");
        this.classroomText.setText("");
    }
    
    public void setInformation(ModelTeacher teacher){
        this.idText.setText(teacher.getId());
        this.last_nameText.setText(teacher.getLast_name());
        this.first_nameText.setText(teacher.getFirst_name());
        if(teacher.getGender().equals("Male")){
            this.gender1Text.setSelected(true);
        }else{
            this.gender2Text.setSelected(true);
        }
        this.birthdayText.setText(teacher.getBirthday());
        this.emailText.setText(teacher.getEmail());
        this.phoneText.setText(teacher.getPhone());
        this.classroomText.setText(teacher.getId_classroom());
    }
    
    public ModelTeacher getInformation(){
        ModelTeacher teacher; 
        
        String id = this.idText.getText();
        String last_name = this.last_nameText.getText();
        String first_name = this.first_nameText.getText();
        String birthday = this.birthdayText.getText();
        String gender; 
        if(gender1Text.isSelected()) gender = gender1Text.getText();
        else gender = gender2Text.getText();
        String phone = this.phoneText.getText();
        String email = this.emailText.getText();
        String id_classroom = this.classroomText.getText();
        teacher = new ModelTeacher(id,last_name,first_name,birthday,gender,phone,email,id_classroom);
        
        return teacher;
    }
    
    public void ViewTable(){
        ArrayList<ModelTeacher> teacherList = serviceTeacher.showInformation();
        
        DefaultTableModel tblModel = (DefaultTableModel) teacherTable.getModel();
        for(ModelTeacher teacher : teacherList){
            String data[] ={teacher.getId(),teacher.getLast_name(), teacher.getFirst_name(),teacher.getBirthday()
                    ,teacher.getGender(),teacher.getPhone(),teacher.getEmail(),teacher.getId_classroom()};
            tblModel.addRow(data);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        headerTeacher = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ibLabel = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        last_nameLabel = new javax.swing.JLabel();
        last_nameText = new javax.swing.JTextField();
        first_nameLabel = new javax.swing.JLabel();
        first_nameText = new javax.swing.JTextField();
        birthdayLabel = new javax.swing.JLabel();
        birthdayText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        gender1Text = new javax.swing.JCheckBox();
        gender2Text = new javax.swing.JCheckBox();
        phoneLabel = new javax.swing.JLabel();
        phoneText = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        classroomLabel = new javax.swing.JLabel();
        classroomText = new javax.swing.JTextField();
        btADD = new javax.swing.JButton();
        btSEARCH = new javax.swing.JButton();
        btDELETE = new javax.swing.JButton();
        btEDIT = new javax.swing.JButton();
        btRETURN = new javax.swing.JButton();
        btREFRESH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacherTable = new javax.swing.JTable();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerTeacher.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headerTeacher.setText("Manager Teacher");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(headerTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        ibLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ibLabel.setText("ID: ");

        idText.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        last_nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        last_nameLabel.setText("Last_name:");

        last_nameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        first_nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        first_nameLabel.setText("First_name: ");
        first_nameLabel.setToolTipText("");

        first_nameText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        birthdayLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        birthdayLabel.setText("Birthday:");

        birthdayText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Gender:");

        gender1Text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gender1Text.setText("Male");

        gender2Text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gender2Text.setText("Fermale");

        phoneLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        phoneLabel.setText("Phone:");

        phoneText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        emailLabel.setText("Email:");

        emailText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        classroomLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        classroomLabel.setText("Classroom:");

        classroomText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btADD.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btADD.setText("ADD");
        btADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btADDActionPerformed(evt);
            }
        });

        btSEARCH.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btSEARCH.setText("SEARCH");
        btSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSEARCHActionPerformed(evt);
            }
        });

        btDELETE.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btDELETE.setText("DELETE");
        btDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDELETEActionPerformed(evt);
            }
        });

        btEDIT.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btEDIT.setText("EDIT");
        btEDIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEDITActionPerformed(evt);
            }
        });

        btRETURN.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btRETURN.setText("RETURN");
        btRETURN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRETURNActionPerformed(evt);
            }
        });

        btREFRESH.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btREFRESH.setText("REFRESH");
        btREFRESH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btREFRESHActionPerformed(evt);
            }
        });

        teacherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Last_name", "First_name", "Birthday", "Gender", "Phone", "Email", "Classroom"
            }
        ));
        teacherTable.setSelectionBackground(new java.awt.Color(153, 255, 255));
        teacherTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(teacherTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(birthdayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(first_nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(last_nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ibLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btADD, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(birthdayText, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                .addComponent(first_nameText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(last_nameText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idText, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btDELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(phoneLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                    .addGap(43, 43, 43)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(phoneText, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                        .addComponent(emailText)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(gender1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(gender2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(classroomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(classroomText, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btEDIT, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btRETURN, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btREFRESH, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ibLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idText))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(last_nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(last_nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(first_nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(first_nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(birthdayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(birthdayText, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(classroomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(classroomText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(gender2Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gender1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btADD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSEARCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDELETE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btEDIT)
                    .addComponent(btRETURN)
                    .addComponent(btREFRESH))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btADDActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) teacherTable.getModel();
        ModelTeacher teacher = getInformation();
        if(teacher.getId().equals("") || teacher.getLast_name().equals("") || teacher.getFirst_name().equals("")
                || teacher.getBirthday().equals("") || teacher.getGender().equals("") || teacher.getEmail().equals("")
                || teacher.getPhone().equals("") || teacher.getId_classroom().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter All Data...");
        }else{
            if(serviceTeacher.checkId(teacher.getId())){
                JOptionPane.showMessageDialog(this, "Enter new Id");
            }else{
                serviceTeacher.addTeacher(teacher);
                JOptionPane.showMessageDialog(this, "Add Data Successfull... !!");
                DefaultInformation();
                tblModel.addRow(new Object[]{teacher.getId(),teacher.getLast_name(),teacher.getFirst_name(),teacher.getBirthday()
                    ,teacher.getGender(),teacher.getPhone(),teacher.getEmail(),teacher.getId_classroom()});
            }
        }
    }//GEN-LAST:event_btADDActionPerformed

    private void btSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSEARCHActionPerformed
        // TODO add your handling code here:
        if(this.idText.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter ID for Search...!!");
        }else{
            if(serviceTeacher.checkId(this.idText.getText())){
                String idSearch = this.idText.getText();
                ModelTeacher teacherSearch = serviceTeacher.searchTeacher(idSearch);
                DefaultTableModel tblModel = (DefaultTableModel) teacherTable.getModel();
                
                int rowLength = tblModel.getRowCount();
                for(int i =0; i< rowLength; i++){
                    if(Objects.equals(teacherSearch.getId(), (String) teacherTable.getValueAt(i, 0))){
                        teacherTable.addRowSelectionInterval(i,i);
                        setInformation(teacherSearch);
                        break;
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "ID don't have in data. Enter Id Again...!");
            }
        }
    }//GEN-LAST:event_btSEARCHActionPerformed

    private void btDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDELETEActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) teacherTable.getModel();
        if(teacherTable.getSelectedRowCount() == 1){
            tblModel.removeRow(teacherTable.getSelectedRow());
            String id_delete = idText.getText();
            serviceTeacher.deleteTeacher(id_delete);
            DefaultInformation();
            JOptionPane.showMessageDialog(this, "Detele Successfull ...!");
        }else{
            if(teacherTable.getSelectedRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Table is empty...");
            }else{
                JOptionPane.showMessageDialog(this, "Please Select Single Row for Delete...");
            }
        }
    }//GEN-LAST:event_btDELETEActionPerformed

    private void btEDITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEDITActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) teacherTable.getModel();
        if(teacherTable.getSelectedRowCount() == 1){
            ModelTeacher teacher = getInformation();
            serviceTeacher.updateTeacher(teacher, tblModel.getValueAt(teacherTable.getSelectedRow(),0).toString());
            
            tblModel.setValueAt(teacher.getId(),teacherTable.getSelectedRow(),0);
            tblModel.setValueAt(teacher.getLast_name(),teacherTable.getSelectedRow(),1);
            tblModel.setValueAt(teacher.getFirst_name(),teacherTable.getSelectedRow(),2);
            tblModel.setValueAt(teacher.getBirthday(),teacherTable.getSelectedRow(),3);
            tblModel.setValueAt(teacher.getGender(),teacherTable.getSelectedRow(),4);
            tblModel.setValueAt(teacher.getPhone(),teacherTable.getSelectedRow(),5);
            tblModel.setValueAt(teacher.getEmail(),teacherTable.getSelectedRow(),6);
            tblModel.setValueAt(teacher.getId_classroom(),teacherTable.getSelectedRow(),7);
            
            JOptionPane.showMessageDialog(this, "Update Successfull...!!");
        }else{
            if(teacherTable.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty...");
            }else{
                JOptionPane.showMessageDialog(this,"Please select Single Row for Update...");
            }
        }
    }//GEN-LAST:event_btEDITActionPerformed

    private void btRETURNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRETURNActionPerformed
        // TODO add your handling code here:
        ViewController viewController = new ViewController();
        viewController.show();
        setVisible(false);
    }//GEN-LAST:event_btRETURNActionPerformed

    private void teacherTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) teacherTable.getModel();
        
        String id = tblModel.getValueAt(teacherTable.getSelectedRow(),0).toString();
        String last_name = tblModel.getValueAt(teacherTable.getSelectedRow(),1).toString();
        String first_name = tblModel.getValueAt(teacherTable.getSelectedRow(),2).toString();
        String birthday = tblModel.getValueAt(teacherTable.getSelectedRow(),3).toString();
        String gender = tblModel.getValueAt(teacherTable.getSelectedRow(),4).toString();
        String phone = tblModel.getValueAt(teacherTable.getSelectedRow(),5).toString();
        String email = tblModel.getValueAt(teacherTable.getSelectedRow(),6).toString();
        String classroom = tblModel.getValueAt(teacherTable.getSelectedRow(),7).toString();
        
        this.idText.setText(id);
        this.last_nameText.setText(last_name);
        this.first_nameText.setText(first_name);
        this.birthdayText.setText(birthday);
        if(gender.equals("Male")){
            this.gender1Text.setSelected(true);
        }else{
            this.gender2Text.setSelected(true);
        }
        this.phoneText.setText(phone);
        this.emailText.setText(email);
        this.classroomText.setText(classroom);
    }//GEN-LAST:event_teacherTableMouseClicked

    private void btREFRESHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btREFRESHActionPerformed
        // TODO add your handling code here:
        DefaultInformation();
        teacherTable.getSelectionModel().clearSelection();
    }//GEN-LAST:event_btREFRESHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewTeacher().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JTextField birthdayText;
    private javax.swing.JButton btADD;
    private javax.swing.JButton btDELETE;
    private javax.swing.JButton btEDIT;
    private javax.swing.JButton btREFRESH;
    private javax.swing.JButton btRETURN;
    private javax.swing.JButton btSEARCH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel classroomLabel;
    private javax.swing.JTextField classroomText;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel first_nameLabel;
    private javax.swing.JTextField first_nameText;
    private javax.swing.JCheckBox gender1Text;
    private javax.swing.JCheckBox gender2Text;
    private javax.swing.JLabel headerTeacher;
    private javax.swing.JLabel ibLabel;
    private javax.swing.JTextField idText;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel last_nameLabel;
    private javax.swing.JTextField last_nameText;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneText;
    private javax.swing.JTable teacherTable;
    // End of variables declaration//GEN-END:variables
}
